---
name: Docker
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
  pull_request:
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
jobs:
  docker-build:
    name: Docker Build
    strategy:
      matrix:
        arch:
          - amd64
          - i386
          - armhf
          - aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Docker Environment
        run:
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Test Docker Build
        run:
          docker build --build-arg ARCH=${{ matrix.arch }} -f packaging/docker/Dockerfile .
